#:kivy 2.2.1

<MainMenu>:
	BoxLayout:
		orientation: 'vertical'
		Button:
			text: 'Next'
			size_hint: 0.15, 0.10 * 3
			pos_hint: {'x': 0, 'y': 1} # x, center_x, right
			on_press:
				root.manager.transition.direction = 'left'
				root.on_click()
		Button:
			text: 'Selection'
		Button:
			text: 'Locations'
			on_press:
				root.manager.transition.direction = 'left'
				root.manager.current = 'LocationScreen'