#:kivy 2.2.1

<View>:
    BoxLayout:
        orientation: 'vertical'
        Button:
            size_hint: 0.15, 0.10
            text: 'back'
            font_size: int((root.height + root.width)*0.02)
            on_press:
                root.manager.transition.direction = 'right'
                root.manager.current = 'LocationScreen'
        ViewLayout:
            # locs: self.locs
            on_kv_post:
                self.test()